### ISSUE TITLE
[📊] Ideas for a better name

### ISSUE THREAD

**Issue by xmollv** [xmollv/Llitgi#28]
I don't like the name `Llitgi`, it was something that came to mind while hacking the first days, but there's no way in the world than somebody that's not from Catalunya, Spain would be able to pronounce it properly.

These are some ideas that I have in mind:

- Calmer for Pocket
- Simplr for Pocket

Feel free to add any of your ideas! I'm terrible at naming things 😬

**Comment by fwigorcferreira** [comment]
Cabron

**Comment by igorcferreira** [comment]
Cabron

**Comment by igorcferreira** [comment]
Poke it

**Comment by fwigorcferreira** [comment]
Poquet

**Comment by igorcferreira** [comment]
Poquet

**Comment by BlueHeisenberg** [comment]
Puke it!

**Comment by BlueHeisenberg** [comment]
Fika
