### ISSUE TITLE
Offline first is a LIE

### ISSUE THREAD

**Issue by igorcferreira** [xmollv/Llitgi#30]
![The cake is a lie](https://orig00.deviantart.net/af24/f/2012/036/c/7/the_cake_is_a_lie_by_bellajynx-d4or9i4.gif)

When using the share extension, or adding a new link, the app needs the internet connection to work. To be "offline first", the app should store, and late sync. So, the person do not loose links when trying to add it offline.

**Comment by xmollv** [comment]
If you don't have internet connection, the share extension displays an error when saving the link. You're right that right now we're not displaying any error to the user if the `add` operation fails from the app itself. I'll open a new issue for this.
